### ISSUE TITLE
DevOp Tools

### ISSUE THREAD

**Issue by eetar1** [Ross-Alexandra/SENG-371-Project-2#3]
We should setup Travis or Jenkins

**Comment by Ross-Alexandra** [comment]
I'm setting up Travis because we don't have a dedicated personal server.

**Comment by Ross-Alexandra** [comment]
Travis-CI setup: https://travis-ci.org/Ross-Alexandra/SENG-371-Project-2
Codecov setup: https://codecov.io/gh/Ross-Alexandra/SENG-371-Project-2/settings/badge

I also setup auto black, and isort (using pre-commit.) These automatically fix our codestyle to be consistent, and automatically deal with our imports.

I'll think on it a bit more after this, but I think that this ticket is complete.... Probably going to change the codecov config a little bit.

**Comment by Ross-Alexandra** [comment]
As of https://github.com/Ross-Alexandra/SENG-371-Project-2/commit/6446f057f0c018f39da7e6dcfc9de2d0e800fe6e, the codecov will only count the code that we add for the actual project (not the included urls, or the settings, etc.)

This is ideal because we don't want to test Django code, only our code.

Closing this for now as I believe these tools should be enough to at least get started.
