### ISSUE TITLE
Docker Configuration

### ISSUE THREAD

**Issue by eetar1** [Ross-Alexandra/SENG-371-Project-2#4]
We need someone to setup Docker and learn how it works

**Comment by Ross-Alexandra** [comment]
As of https://github.com/Ross-Alexandra/SENG-371-Project-2/commit/d545c2e8dde0cbb1ea97714227ccbf2720febbaf, the docker has been setup, and a basic walkthrough of setting it up (for linux) has been created.

Due to a lack of AC on this ticket, I'm not exactly sure when this should be done. That given, I'm closing this ticket now, if there's anything else that needs to be done, feel free to reopen it.
